# Generated by Django 3.0.14 on 2022-03-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EssayReviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essayreview',
            name='Title',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='essayreview',
            name='Topic',
            field=models.CharField(choices=[('Art', 'Art'), ('Anatomy', 'Anatomy'), ('Blockchain', 'Blockchain'), ('Business', 'Business'), ('Comedy', 'Comedy'), ('Communication', 'Communication'), ('Design', 'Design'), ('Education', 'Education'), ('Engineering', 'Engineering'), ('Finance', 'Finance'), ('Health', 'Health'), ('History', 'History'), ('Games', 'Games'), ('Law', 'Law'), ('Linguistics', 'Linguistics'), ('Literature', 'Literature'), ('Politics', 'Politics'), ('Philosophy', 'Philosophy'), ('Religion', 'Religion'), ('Sciences', 'Sciences'), ('Others', 'Others')], max_length=255),
        ),
    ]
