# Generated by Django 3.0.14 on 2022-03-23 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('EssayReviews', '0002_auto_20220321_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essayreview',
            old_name='Reviewer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='essayreview',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='essayreview',
            name='Topic',
        ),
        migrations.AddField(
            model_name='essayreview',
            name='content_type',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='essayreview',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='essayreview',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EssayReviews.EssayReview'),
        ),
        migrations.AlterField(
            model_name='essayreview',
            name='EssayReviewContent',
            field=models.TextField(null=True),
        ),
    ]
