# Generated by Django 3.0.14 on 2022-03-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220317_1340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_Us',
        ),
    ]
