# Generated by Django 3.0.14 on 2022-03-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_contact_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinglist',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
