# Generated by Django 3.0.14 on 2022-03-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Essay', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essay',
            old_name='No_of_Reviewer',
            new_name='No_of_Reviewers',
        ),
        migrations.RenameField(
            model_name='essay',
            old_name='Author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='Title',
        ),
        migrations.AddField(
            model_name='essay',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='essay',
            name='read_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='essay',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='title',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='essay',
            name='EssayContent',
            field=models.TextField(null=True),
        ),
    ]
