# Generated by Django 3.0.14 on 2022-03-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Essay', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='essay',
            options={'ordering': ['-Created_at']},
        ),
        migrations.AddField(
            model_name='essay',
            name='EssayContent',
            field=models.TextField(default=False),
        ),
    ]
